//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testify.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testify.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null inner exception was specified..
        /// </summary>
        internal static string AssertionException_InnerExceptionNull {
            get {
                return ResourceManager.GetString("AssertionException_InnerExceptionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}---&gt; (Inner Exception #{2}) {3}{4}{5}.
        /// </summary>
        internal static string AssertionException_ToString {
            get {
                return ResourceManager.GetString("AssertionException_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An assertion failed..
        /// </summary>
        internal static string AssertionException_UnspecifiedAssertionMessage {
            get {
                return ResourceManager.GetString("AssertionException_UnspecifiedAssertionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (null).
        /// </summary>
        internal static string Common_NullInMessages {
            get {
                return ResourceManager.GetString("Common_NullInMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Common_ObjectString {
            get {
                return ResourceManager.GetString("Common_ObjectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caught the expected exception type &lt;{0}&gt;, but additional assertions failed. {1}.
        /// </summary>
        internal static string FrameworkMessage_AdditionalAssertionsFailed {
            get {
                return ResourceManager.GetString("FrameworkMessage_AdditionalAssertionsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed. {1}.
        /// </summary>
        internal static string FrameworkMessage_AssertionFailed {
            get {
                return ResourceManager.GetString("FrameworkMessage_AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Same elements.).
        /// </summary>
        internal static string FrameworkMessage_BothCollectionsSameElements {
            get {
                return ResourceManager.GetString("FrameworkMessage_BothCollectionsSameElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Same reference.).
        /// </summary>
        internal static string FrameworkMessage_BothCollectionsSameReference {
            get {
                return ResourceManager.GetString("FrameworkMessage_BothCollectionsSameReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string FrameworkMessage_CollectionEqualReason {
            get {
                return ResourceManager.GetString("FrameworkMessage_CollectionEqualReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string FrameworkMessage_CollectionNotEqualReason {
            get {
                return ResourceManager.GetString("FrameworkMessage_CollectionNotEqualReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; does not contain string &apos;{1}&apos;. {2}.
        /// </summary>
        internal static string FrameworkMessage_ContainsFailMsg {
            get {
                return ResourceManager.GetString("FrameworkMessage_ContainsFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected exception: &lt;{0}&gt;. The action did not throw any exceptions. {1}.
        /// </summary>
        internal static string FrameworkMessage_DidNotThrow {
            get {
                return ResourceManager.GetString("FrameworkMessage_DidNotThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; matches pattern &apos;{1}&apos;. {2}.
        /// </summary>
        internal static string FrameworkMessage_DoesNotMatchFailMsg {
            get {
                return ResourceManager.GetString("FrameworkMessage_DoesNotMatchFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate item found: &lt;{0}&gt;. {1}.
        /// </summary>
        internal static string FrameworkMessage_DuplicateFound {
            get {
                return ResourceManager.GetString("FrameworkMessage_DuplicateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Elements at index {0} do not match. Expected element: &lt;{1}&gt;. Actual element: &lt;{2}&gt;.).
        /// </summary>
        internal static string FrameworkMessage_ElementsAtIndexDoNotMatch {
            get {
                return ResourceManager.GetString("FrameworkMessage_ElementsAtIndexDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; does not end with string &apos;{1}&apos;. {2}.
        /// </summary>
        internal static string FrameworkMessage_EndsWithFailMsg {
            get {
                return ResourceManager.GetString("FrameworkMessage_EndsWithFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a difference no greater than &lt;{0}&gt; between expected value &lt;{1}&gt; and actual value &lt;{2}&gt;. {3}.
        /// </summary>
        internal static string FrameworkMessage_IsEqualToDeltaFailMsg {
            get {
                return ResourceManager.GetString("FrameworkMessage_IsEqualToDeltaFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected: &lt;{0}&gt;. Actual: &lt;{1}&gt;. {2}.
        /// </summary>
        internal static string FrameworkMessage_IsEqualToFailMsg {
            get {
                return ResourceManager.GetString("FrameworkMessage_IsEqualToFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected: &lt;{0} ({1})&gt;. Actual: &lt;{2} ({3})&gt;. {4}.
        /// </summary>
        internal static string FrameworkMessage_IsEqualToFailTypesMsg {
            get {
                return ResourceManager.GetString("FrameworkMessage_IsEqualToFailTypesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected type: {0}. Actual type: {1}. {2}.
        /// </summary>
        internal static string FrameworkMessage_IsInstanceOfTypeFailMsg {
            get {
                return ResourceManager.GetString("FrameworkMessage_IsInstanceOfTypeFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a difference greater than &lt;{0}&gt; between expected value &lt;{1}&gt; and actual value &lt;{2}&gt;. {3}.
        /// </summary>
        internal static string FrameworkMessage_IsNotEqualToDeltaFailMsg {
            get {
                return ResourceManager.GetString("FrameworkMessage_IsNotEqualToDeltaFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected any value except: &lt;{0}&gt;. Actual: &lt;{1}&gt;. {2}.
        /// </summary>
        internal static string FrameworkMessage_IsNotEqualToFailMsg {
            get {
                return ResourceManager.GetString("FrameworkMessage_IsNotEqualToFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong type: {0}. Actual type: {1}. {2}.
        /// </summary>
        internal static string FrameworkMessage_IsNotInstanceOfTypeFailMsg {
            get {
                return ResourceManager.GetString("FrameworkMessage_IsNotInstanceOfTypeFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; does not match pattern &apos;{1}&apos;. {2}.
        /// </summary>
        internal static string FrameworkMessage_MatchesFailMsg {
            get {
                return ResourceManager.GetString("FrameworkMessage_MatchesFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is invalid. The value cannot be null. {1}.
        /// </summary>
        internal static string FrameworkMessage_NullParameterToAssert {
            get {
                return ResourceManager.GetString("FrameworkMessage_NullParameterToAssert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Different number of elements.).
        /// </summary>
        internal static string FrameworkMessage_NumberOfElementsDiff {
            get {
                return ResourceManager.GetString("FrameworkMessage_NumberOfElementsDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; does not start with string &apos;{1}&apos;. {2}.
        /// </summary>
        internal static string FrameworkMessage_StartsWithFailMsg {
            get {
                return ResourceManager.GetString("FrameworkMessage_StartsWithFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected exception: &lt;{0}&gt;. Actual exception: &lt;{1}&gt;. {2}.
        /// </summary>
        internal static string FrameworkMessage_UnexpectedException {
            get {
                return ResourceManager.GetString("FrameworkMessage_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element at index {0} is not of expected type: &lt;{1}&gt;. Actual type: &lt;{2}&gt;. {3}.
        /// </summary>
        internal static string FrameworMessage_UnexpectedTypeAt {
            get {
                return ResourceManager.GetString("FrameworMessage_UnexpectedTypeAt", resourceCulture);
            }
        }
    }
}
